import { provideIcons } from '@ng-icons/core';
import {
  lucideCircleAlert,
  lucideCircleCheck,
  lucideCamera,
  lucideBell,
  lucideGift,
  lucideGem,
  lucideGlobe,
  lucideFolderOpen,
  lucideClock,
  lucideHouse,
  lucideMenu,
  lucideMessageCircle,
  lucidePill,
  lucidePlus,
  lucideQrCode,
  lucideReceiptText,
  lucideUsers,
  lucideRotateCcw,
  lucideX,
} from '@ng-icons/lucide';

export const provideLucideIcons = () =>
  provideIcons({
    lucideCircleAlert,
    lucideCircleCheck,
    lucideCamera,
    lucideBell,
    lucideGift,
    lucideGem,
    lucideGlobe,
    lucideFolderOpen,
    lucideClock,
    lucideHouse,
    lucideMenu,
    lucideMessageCircle,
    lucidePill,
    lucidePlus,
    lucideQrCode,
    lucideReceiptText,
    lucideUsers,
    lucideRotateCcw,
    lucideX,
  });
