<?php
declare(strict_types=1);
namespace App\Controller;
use App\Entity\MediaAsset; use App\Entity\NewsPost; use App\Entity\Reward; use App\Entity\User; use App\Repository\TenantMembershipRepository; use App\Service\ActiveTenantProvider; use App\Service\ImageProcessor; use Doctrine\ORM\EntityManagerInterface; use Symfony\Bundle\SecurityBundle\Security; use Symfony\Component\HttpFoundation\File\UploadedFile; use Symfony\Component\HttpFoundation\JsonResponse; use Symfony\Component\HttpFoundation\Request; use Symfony\Component\HttpFoundation\Response; use Symfony\Component\Routing\Attribute\Route; use Symfony\Component\String\Slugger\SluggerInterface;
final class ApiAdminMediaController {
 public function __construct(private readonly EntityManagerInterface $em,private readonly Security $security,private readonly ActiveTenantProvider $tenant,private readonly TenantMembershipRepository $memberships,private readonly ImageProcessor $images){}
 #[Route('/api/v1/admin/media',methods:['GET'])] public function list(Request $request): JsonResponse { if(!$this->admin())return new JsonResponse(['message'=>'Forbidden.'],403); $assets=$this->em->getRepository(MediaAsset::class)->findBy(['tenant'=>$this->tenant->get(),'visibility'=>'public'],['createdAt'=>'DESC']); return new JsonResponse(['media'=>array_map(fn(MediaAsset $asset)=>$this->serialize($asset,$request),$assets)]); }
 #[Route('/api/v1/admin/media',methods:['POST'])] public function upload(Request $request,SluggerInterface $slugger): JsonResponse { if(!$this->admin())return new JsonResponse(['message'=>'Forbidden.'],403); $files=$request->files->all('images'); if($files===[])$files=$request->files->get('image') instanceof UploadedFile?[$request->files->get('image')]:[]; $created=[]; foreach($files as $file){if(!$file instanceof UploadedFile||$file->getSize()>5*1024*1024||!in_array($file->getMimeType(),['image/jpeg','image/png','image/webp'],true))return new JsonResponse(['message'=>'Erlaubt sind PNG, JPEG oder WebP bis 5 MB.'],422);$dir=dirname(__DIR__,2).'/public/uploads/media';if(!is_dir($dir)&&!mkdir($dir,0775,true)&&!is_dir($dir))return new JsonResponse(['message'=>'Upload-Verzeichnis ist nicht verfügbar.'],500);$name=$slugger->slug(pathinfo($file->getClientOriginalName(),PATHINFO_FILENAME)).'-'.bin2hex(random_bytes(8)).'.jpg';if(!$this->images->saveAdminImage($file,$dir.'/'.$name))return new JsonResponse(['message'=>'Bild konnte nicht verarbeitet werden.'],422);$size=@getimagesize($dir.'/'.$name);$asset=new MediaAsset($this->tenant->get(),null,'/uploads/media/'.$name,$file->getClientOriginalName(),'public','library',(int)($size[0]??0),(int)($size[1]??0),(int)filesize($dir.'/'.$name));$this->em->persist($asset);$created[]=$asset;} if($created===[])return new JsonResponse(['message'=>'Bitte wählen Sie mindestens ein Bild aus.'],422);$this->em->flush();return new JsonResponse(['media'=>array_map(fn(MediaAsset $asset)=>$this->serialize($asset,$request),$created)],201); }
 #[Route('/api/v1/admin/media/{id}',methods:['DELETE'])] public function delete(int $id): JsonResponse|Response { if(!$this->admin())return new JsonResponse(['message'=>'Forbidden.'],403); $asset=$this->em->getRepository(MediaAsset::class)->find($id); if(!$asset instanceof MediaAsset||$asset->getTenant()!==$this->tenant->get())return new JsonResponse(['message'=>'Bild nicht gefunden.'],404); $usage=$this->usage($asset); if($usage!==[])return new JsonResponse(['message'=>'Das Bild wird noch verwendet und kann nicht gelöscht werden.','usage'=>$usage],409); $file=dirname(__DIR__,2).'/public'.$asset->getPath(); if(is_file($file))unlink($file); $this->em->remove($asset);$this->em->flush();return new Response(status:204); }
 private function usage(MediaAsset $asset): array {$path=$asset->getPath();$tenant=$this->tenant->get();$result=[];foreach($this->em->getRepository(Reward::class)->findBy(['tenant'=>$tenant,'imagePath'=>$path]) as $reward){$result[]=['type'=>'reward','label'=>$reward->getTitle(),'editUrl'=>'/praemien/'.$reward->getId()];}foreach($this->em->getRepository(NewsPost::class)->findBy(['tenant'=>$tenant,'imagePath'=>$path]) as $post){$result[]=['type'=>'news_cover','label'=>$post->getTitle(),'editUrl'=>'/inhalte/'.$post->getId()];}$posts=$this->em->createQueryBuilder()->select('post')->from(NewsPost::class,'post')->where('post.tenant=:tenant AND post.bodyHtml LIKE :path')->setParameter('tenant',$tenant)->setParameter('path','%'.$path.'%')->getQuery()->getResult();foreach($posts as $post){$result[]=['type'=>'news_content','label'=>$post->getTitle(),'editUrl'=>'/inhalte/'.$post->getId()];}foreach($this->em->getRepository(Reward::class)->findBy(['tenant'=>$tenant]) as $reward){if(str_contains($reward->getDescription(),$path)){$result[]=['type'=>'reward_content','label'=>$reward->getTitle(),'editUrl'=>'/praemien/'.$reward->getId()];}}return $result;}
 private function admin():bool{$u=$this->security->getUser();if(!$u instanceof User)return false;$m=$this->memberships->findForUserAndTenant($u,$this->tenant->get());return $m&&[]!==array_intersect(['ROLE_TENANT_STAFF','ROLE_TENANT_ADMIN'],$m->getRoles());} private function serialize(MediaAsset $a,Request $r):array{return ['id'=>$a->getId(),'url'=>$r->getSchemeAndHttpHost().$a->getPath(),'name'=>$a->getOriginalName(),'width'=>$a->getWidth(),'height'=>$a->getHeight(),'createdAt'=>$a->getCreatedAt()->format(DATE_ATOM)];}
}
