<?php
declare(strict_types=1);
namespace App\Controller;
use App\Entity\{Coupon,User}; use App\Repository\TenantMembershipRepository; use App\Service\{ActiveTenantProvider,RichTextSanitizer}; use Doctrine\ORM\EntityManagerInterface; use Symfony\Bundle\SecurityBundle\Security; use Symfony\Component\HttpFoundation\{JsonResponse,Request,Response}; use Symfony\Component\Routing\Attribute\Route;
final class ApiCouponController {
 public function __construct(private readonly EntityManagerInterface $em,private readonly ActiveTenantProvider $tenant,private readonly TenantMembershipRepository $memberships,private readonly Security $security,private readonly RichTextSanitizer $richText){}
 #[Route('/api/v1/coupons',methods:['GET'])] public function customer(Request $request):JsonResponse{$now=new \DateTimeImmutable();$items=$this->em->createQueryBuilder()->select('coupon')->from(Coupon::class,'coupon')->where('coupon.tenant=:tenant')->andWhere('coupon.isVisible=true')->andWhere('(coupon.availableFrom IS NULL OR coupon.availableFrom<=:now)')->andWhere('(coupon.availableUntil IS NULL OR coupon.availableUntil>=:now)')->orderBy('coupon.id','DESC')->setParameter('tenant',$this->tenant->get())->setParameter('now',$now)->getQuery()->getResult();return new JsonResponse(['coupons'=>array_map(fn(Coupon $coupon)=>$this->serialize($coupon,$request),$items)]);}
 #[Route('/api/v1/admin/coupons',methods:['GET'])] public function adminList(Request $request):JsonResponse{if(!$this->admin())return new JsonResponse(['message'=>'Forbidden.'],403);$items=$this->em->getRepository(Coupon::class)->findBy(['tenant'=>$this->tenant->get()],['id'=>'DESC']);return new JsonResponse(['coupons'=>array_map(fn(Coupon $coupon)=>$this->serialize($coupon,$request),$items)]);}
 #[Route('/api/v1/admin/coupons/{id}',methods:['GET'])] public function one(int $id,Request $request):JsonResponse{$coupon=$this->find($id);return $this->admin()&&$coupon?new JsonResponse(['coupon'=>$this->serialize($coupon,$request)]):new JsonResponse(['message'=>'Gutschein nicht gefunden.'],404);}
 #[Route('/api/v1/admin/coupons',methods:['POST'])] public function create(Request $request):JsonResponse{if(!$this->admin())return new JsonResponse(['message'=>'Forbidden.'],403);[$title,$subtitle,$description,$from,$until]=$this->data($request);if($title===''||$subtitle===''||$description===''||$from===false||$until===false||($from&&$until&&$from>$until))return new JsonResponse(['message'=>'Ungültige Gutscheinangaben.'],422);$coupon=new Coupon($this->tenant->get(),$title,$subtitle,$description,(string)$request->request->get('mediaPath',''),'true'===$request->request->get('isVisible','true'),$from,$until);$this->em->persist($coupon);$this->em->flush();return new JsonResponse(['coupon'=>$this->serialize($coupon,$request)],201);}
 #[Route('/api/v1/admin/coupons/{id}/update',methods:['POST'])] public function update(int $id,Request $request):JsonResponse{if(!$this->admin()||!($coupon=$this->find($id)))return new JsonResponse(['message'=>'Gutschein nicht gefunden.'],404);[$title,$subtitle,$description,$from,$until]=$this->data($request);if($title===''||$subtitle===''||$description===''||$from===false||$until===false||($from&&$until&&$from>$until))return new JsonResponse(['message'=>'Ungültige Gutscheinangaben.'],422);$coupon->update($title,$subtitle,$description,$request->request->has('mediaPath')?(string)$request->request->get('mediaPath'):$coupon->getImagePath(),'true'===$request->request->get('isVisible','true'),$from,$until);$this->em->flush();return new JsonResponse(['coupon'=>$this->serialize($coupon,$request)]);}
 #[Route('/api/v1/admin/coupons/{id}/visibility',methods:['PATCH'])] public function visibility(int $id,Request $request):JsonResponse{$coupon=$this->find($id);$visible=$request->toArray()['isVisible']??null;if(!$this->admin()||!$coupon||!is_bool($visible))return new JsonResponse(['message'=>'Ungültig.'],422);$coupon->setVisible($visible);$this->em->flush();return new JsonResponse(['coupon'=>$this->serialize($coupon,$request)]);}
 private function data(Request $request):array{$from=$this->date($request->request->get('availableFrom'));$until=$this->date($request->request->get('availableUntil'));return [trim((string)$request->request->get('title','')),trim((string)$request->request->get('subtitle','')),$this->richText->sanitize((string)$request->request->get('description','')),$from,$until];} private function date(mixed $value):\DateTimeImmutable|false|null{if($value===null||$value==='')return null;if(!is_string($value))return false;$date=\DateTimeImmutable::createFromFormat('Y-m-d\\TH:i',$value);return $date!==false&&$date->format('Y-m-d\\TH:i')===$value?$date:false;} private function find(int $id):?Coupon{$coupon=$this->em->getRepository(Coupon::class)->find($id);return $coupon instanceof Coupon&&$coupon->getTenant()===$this->tenant->get()?$coupon:null;} private function admin():bool{$user=$this->security->getUser();if(!$user instanceof User)return false;$member=$this->memberships->findForUserAndTenant($user,$this->tenant->get());return $member&&[]!==array_intersect(['ROLE_TENANT_STAFF','ROLE_TENANT_ADMIN'],$member->getRoles());} private function serialize(Coupon $coupon,Request $request):array{return ['id'=>$coupon->getId(),'title'=>$coupon->getTitle(),'subtitle'=>$coupon->getSubtitle(),'description'=>$coupon->getDescription(),'imageUrl'=>$coupon->getImagePath()===''?null:$request->getSchemeAndHttpHost().$coupon->getImagePath(),'isVisible'=>$coupon->isVisible(),'availableFrom'=>$coupon->getAvailableFrom()?->format(DATE_ATOM),'availableUntil'=>$coupon->getAvailableUntil()?->format(DATE_ATOM)];}
}
