<?php
declare(strict_types=1); namespace App\Controller;
use App\Entity\{ActiveRedemption,PointTransaction,User}; use App\Repository\TenantMembershipRepository; use App\Service\ActiveTenantProvider; use Doctrine\ORM\EntityManagerInterface; use Symfony\Bundle\SecurityBundle\Security; use Symfony\Component\HttpFoundation\{JsonResponse,Request}; use Symfony\Component\Routing\Attribute\Route;
final class ApiPointTransactionController {
 private const ADMIN=['ROLE_TENANT_STAFF','ROLE_TENANT_ADMIN'];
 public function __construct(private EntityManagerInterface $em,private Security $security,private ActiveTenantProvider $tenant,private TenantMembershipRepository $memberships){}
#[Route('/api/v1/admin/point-transactions',methods:['GET'])] public function list(Request $request):JsonResponse {if(!$this->admin())return new JsonResponse(['message'=>'Forbidden.'],403);$query=trim((string)$request->query->get('query',''));$activeOnly='true'===$request->query->get('activeOnly');$qb=$this->em->createQueryBuilder()->select('t,a,u')->from(PointTransaction::class,'t')->join('t.account','a')->join('a.owner','u')->where('a.tenant=:tenant')->setParameter('tenant',$this->tenant->get())->orderBy('t.createdAt','DESC')->setMaxResults(100);if($query!==''){$qb->andWhere('u.username LIKE :query OR u.id=:id')->setParameter('query','%'.$query.'%')->setParameter('id',ctype_digit($query)?(int)$query:-1);}if($activeOnly){$qb->join(ActiveRedemption::class,'r','WITH','r.account=a')->andWhere('r.status=:status AND r.validUntil > :now')->setParameter('status','active')->setParameter('now',new \DateTimeImmutable());}$transactions=$qb->getQuery()->getResult();return new JsonResponse(['transactions'=>array_map(fn(PointTransaction $t)=>['id'=>$t->getId(),'points'=>$t->getPoints(),'type'=>$t->getType(),'label'=>$t->getLabel(),'createdAt'=>$t->getCreatedAt()->format(DATE_ATOM),'customer'=>['id'=>$t->getAccount()->getOwner()->getId(),'username'=>$t->getAccount()->getOwner()->getUsername(),'displayName'=>$t->getAccount()->getOwner()->getDisplayName(),'profileImageUrl'=>$t->getAccount()->getOwner()->getProfileImagePath()===null?null:$request->getSchemeAndHttpHost().$t->getAccount()->getOwner()->getProfileImagePath()]],$transactions)]);}
 private function admin():bool{$user=$this->security->getUser();if(!$user instanceof User)return false;$m=$this->memberships->findForUserAndTenant($user,$this->tenant->get());return $m&&[]!==array_intersect(self::ADMIN,$m->getRoles());}
}
