<?php
declare(strict_types=1); namespace App\Controller;
use App\Entity\{ActiveRedemption,PointAccount,PointTransaction,Reward,User}; use App\Repository\TenantMembershipRepository; use App\Service\ActiveTenantProvider; use Doctrine\ORM\EntityManagerInterface; use Symfony\Bundle\SecurityBundle\Security; use Symfony\Component\HttpFoundation\{JsonResponse,Request,Response}; use Symfony\Component\Routing\Attribute\Route;
final class ApiRedemptionController {
 private const ADMIN=['ROLE_TENANT_STAFF','ROLE_TENANT_ADMIN'];
 public function __construct(private EntityManagerInterface $em,private Security $security,private ActiveTenantProvider $tenant,private TenantMembershipRepository $memberships){}
 #[Route('/api/v1/rewards/redeem',methods:['POST'])] public function redeem(Request $request):JsonResponse { $user=$this->security->getUser(); if(!$user instanceof User)return new JsonResponse(['message'=>'Unauthorized.'],401); $data=$request->toArray();$selections=$data['selections']??[];if(!is_array($selections)||[]===$selections)return new JsonResponse(['message'=>'Invalid selection.'],422); try{return $this->em->wrapInTransaction(function()use($user,$selections,$request){$account=$this->account($user);$this->em->lock($account,\Doctrine\DBAL\LockMode::PESSIMISTIC_WRITE);foreach($this->em->getRepository(ActiveRedemption::class)->findBy(['account'=>$account]) as $active){if($active->isActive())return new JsonResponse(['message'=>'An active redemption already exists.'],409);} $total=0;$titles=[];foreach($selections as $selection){$reward=$this->em->getRepository(Reward::class)->find((int)($selection['rewardId']??0));$quantity=(int)($selection['quantity']??0);if(!$reward instanceof Reward||$reward->getTenant()!==$this->tenant->get()||!$reward->isVisible()||$quantity<1)return new JsonResponse(['message'=>'Invalid selection.'],422);$total+=$reward->getRequiredPoints()*$quantity;$titles[]=$quantity.'× '.$reward->getTitle();} if($this->balance($account)<$total)return new JsonResponse(['message'=>'Insufficient points.'],422);$redemption=new ActiveRedemption($account,$total,implode(', ',$titles));$this->em->persist($redemption);$this->em->persist(new PointTransaction($account,-$total,'redemption',$redemption->getSummary()));$this->em->flush();return new JsonResponse(['redemption'=>$this->serialize($redemption,$request),'remainingPoints'=>$this->balance($account)]);});}catch(\Throwable){return new JsonResponse(['message'=>'Could not create redemption.'],500);} }
 #[Route('/api/v1/admin/redemptions/active',methods:['GET'])] public function active(Request $request):JsonResponse {if(!$this->admin())return new JsonResponse(['message'=>'Forbidden.'],403);$items=[];foreach($this->em->getRepository(ActiveRedemption::class)->findBy(['status'=>'active']) as $item){if($item->isActive())$items[]=$this->serialize($item,$request);}return new JsonResponse(['redemptions'=>$items]);}
 #[Route('/api/v1/rewards/active',methods:['GET'])] public function customerActive(Request $request):JsonResponse {$user=$this->security->getUser();if(!$user instanceof User)return new JsonResponse(['message'=>'Unauthorized.'],401);$account=$this->em->getRepository(PointAccount::class)->findOneBy(['owner'=>$user,'tenant'=>$this->tenant->get()]);if(!$account instanceof PointAccount)return new JsonResponse(['redemption'=>null]);foreach($this->em->getRepository(ActiveRedemption::class)->findBy(['account'=>$account,'status'=>'active']) as $item){if($item->isActive())return new JsonResponse(['redemption'=>$this->serialize($item,$request)]);}return new JsonResponse(['redemption'=>null]);}
 #[Route('/api/v1/admin/redemptions/{id}/cancel',methods:['POST'])] public function cancel(int $id):Response {if(!$this->admin())return new JsonResponse(['message'=>'Forbidden.'],403);$item=$this->em->getRepository(ActiveRedemption::class)->find($id);if(!$item instanceof ActiveRedemption||!$item->isActive())return new JsonResponse(['message'=>'Not found.'],404);$item->cancel();$this->em->persist(new PointTransaction($item->getAccount(),$item->getPoints(),'redemption_cancellation','Abbruch: '.$item->getSummary()));$this->em->flush();return new Response(status:204);}
 private function account(User $user):PointAccount {$account=$this->em->getRepository(PointAccount::class)->findOneBy(['owner'=>$user,'tenant'=>$this->tenant->get()]);if($account instanceof PointAccount)return $account;$account=new PointAccount($this->tenant->get(),$user);$this->em->persist($account);$this->em->flush();$this->em->persist(new PointTransaction($account,1230,'initial_credit','Startguthaben'));$this->em->flush();return $account;}
 private function balance(PointAccount $account):int {$sum=$this->em->createQuery('SELECT COALESCE(SUM(t.points),0) FROM App\\Entity\\PointTransaction t WHERE t.account=:account')->setParameter('account',$account)->getSingleScalarResult();return (int)$sum;}
 private function admin():bool {$user=$this->security->getUser();if(!$user instanceof User)return false;$member=$this->memberships->findForUserAndTenant($user,$this->tenant->get());return $member&&[]!==array_intersect(self::ADMIN,$member->getRoles());}
 private function serialize(ActiveRedemption $r,Request $request):array{$user=$r->getAccount()->getOwner();return ['id'=>$r->getId(),'summary'=>$r->getSummary(),'points'=>$r->getPoints(),'validUntil'=>$r->getValidUntil()->format(DATE_ATOM),'customer'=>$user->getDisplayName(),'customerDetails'=>['id'=>$user->getId(),'displayName'=>$user->getDisplayName(),'username'=>$user->getUsername(),'profileImageUrl'=>$user->getProfileImagePath()===null?null:$request->getSchemeAndHttpHost().$user->getProfileImagePath()]];}
}
