import { Component, inject, signal } from '@angular/core';
import { RichTextEditorComponent } from '../../shared/rich-text-editor.component';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { AdminNewsService } from '../../core/news/admin-news.service';
import { MediaPickerComponent, type PickedMedia } from '../../shared/media-picker.component';

@Component({ selector: 'app-news-editor', imports: [FormsModule, RouterLink, MediaPickerComponent, RichTextEditorComponent], templateUrl: './news-editor.component.html', styleUrl: './news-editor.component.css' })
export class NewsEditorComponent {
  private readonly news = inject(AdminNewsService); private readonly route = inject(ActivatedRoute); private readonly router = inject(Router);
  private postId: number | null = null; private image: File | null = null; protected bodyHtml = '';
  private selectedMediaPath: string | null = null;
  protected readonly isLoading = signal(false); protected readonly isSaving = signal(false); protected readonly error = signal(''); protected readonly imagePreviewUrl = signal<string | null>(null); protected readonly removeExistingImage = signal(false); protected readonly editorState = signal(0);
  protected title = ''; protected subtitle = ''; protected publishedAt = this.toInputValue(new Date().toISOString()); protected showFrom = ''; protected showUntil = ''; protected isVisible = true;
  constructor() { const id = Number(this.route.snapshot.paramMap.get('id')); if (Number.isInteger(id) && id > 0) { this.postId = id; void this.load(id); } }
  protected get isEdit(): boolean { return this.postId !== null; }
  protected selectCoverMedia(image: PickedMedia): void { this.selectedMediaPath = new URL(image.url).pathname; this.image = null; this.removeExistingImage.set(false); this.imagePreviewUrl.set(image.url); }
  protected selectImage(event: Event): void { this.setImage((event.target as HTMLInputElement).files?.[0] ?? null); } protected dragOver(event: DragEvent): void { event.preventDefault(); } protected dropImage(event: DragEvent): void { event.preventDefault(); this.setImage(event.dataTransfer?.files.item(0) ?? null); } protected removeImage(): void { this.image = null; this.selectedMediaPath = null; this.imagePreviewUrl.set(null); this.removeExistingImage.set(true); }
  protected async save(): Promise<void> { const bodyHtml = this.bodyHtml.trim(); if (!this.title.trim() || !this.subtitle.trim() || this.isEmpty(bodyHtml)) { this.error.set('Bitte füllen Sie alle Pflichtfelder aus.'); return; } const data = new FormData(); data.set('title', this.title.trim()); data.set('subtitle', this.subtitle.trim()); data.set('bodyHtml', bodyHtml); data.set('publishedAt', this.publishedAt); data.set('showFrom', this.showFrom); data.set('showUntil', this.showUntil); data.set('isVisible', String(this.isVisible)); data.set('removeImage', String(this.removeExistingImage())); if (this.selectedMediaPath) data.set('mediaPath', this.selectedMediaPath); if (this.image) data.set('image', this.image); this.isSaving.set(true); this.error.set(''); try { if (this.postId === null) await this.news.create(data); else await this.news.update(this.postId, data); await this.router.navigateByUrl('/inhalte'); } catch { this.error.set('Der Beitrag konnte nicht gespeichert werden.'); } finally { this.isSaving.set(false); } }
  private async load(id: number): Promise<void> { this.isLoading.set(true); try { const post = await this.news.get(id); this.title = post.title; this.subtitle = post.subtitle; this.publishedAt = this.toInputValue(post.publishedAt); this.showFrom = post.showFrom ? this.toInputValue(post.showFrom) : ''; this.showUntil = post.showUntil ? this.toInputValue(post.showUntil) : ''; this.isVisible = post.isVisible; this.imagePreviewUrl.set(post.imageUrl); this.bodyHtml = post.bodyHtml; } catch { this.error.set('Der Beitrag konnte nicht geladen werden.'); } finally { this.isLoading.set(false); } }
  private setImage(file: File | null): void { if (!file) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 5 * 1024 * 1024) { this.error.set('Erlaubt sind PNG, JPEG oder WebP bis 5 MB.'); return; } this.image = file; this.removeExistingImage.set(false); this.imagePreviewUrl.set(URL.createObjectURL(file)); }
  private isEmpty(html: string): boolean { return html.replace(/<[^>]+>/g, '').replace(/&nbsp;/g, ' ').trim() === ''; } private toInputValue(value: string): string { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
}
