import { AfterViewInit, Component, ElementRef, OnDestroy, inject, signal, viewChild } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { Editor } from '@tiptap/core';
import Image from '@tiptap/extension-image';
import Link from '@tiptap/extension-link';
import StarterKit from '@tiptap/starter-kit';
import { AdminNewsService } from '../../core/news/admin-news.service';

@Component({ selector: 'app-news-editor', imports: [FormsModule, RouterLink], templateUrl: './news-editor.component.html', styleUrl: './news-editor.component.css' })
export class NewsEditorComponent implements AfterViewInit, OnDestroy {
  private readonly news = inject(AdminNewsService); private readonly route = inject(ActivatedRoute); private readonly router = inject(Router);
  private readonly host = viewChild.required<ElementRef<HTMLElement>>('editorHost'); private editor: Editor | null = null; private postId: number | null = null; private image: File | null = null; private bodyHtml = '';
  protected readonly isLoading = signal(false); protected readonly isSaving = signal(false); protected readonly error = signal(''); protected readonly imagePreviewUrl = signal<string | null>(null); protected readonly removeExistingImage = signal(false); protected readonly editorState = signal(0);
  protected title = ''; protected subtitle = ''; protected publishedAt = this.toInputValue(new Date().toISOString()); protected showFrom = ''; protected showUntil = ''; protected isVisible = true;
  constructor() { const id = Number(this.route.snapshot.paramMap.get('id')); if (Number.isInteger(id) && id > 0) { this.postId = id; void this.load(id); } }
  ngAfterViewInit(): void { this.editor = new Editor({ element: this.host().nativeElement, extensions: [StarterKit.configure({ heading: { levels: [2, 3] } }), Link.configure({ autolink: true, defaultProtocol: 'https://', openOnClick: false }), Image.configure({ allowBase64: false })], content: this.bodyHtml, editorProps: { attributes: { class: 'editor-content', 'aria-label': 'Detailtext' } }, onUpdate: ({ editor }) => { this.bodyHtml = editor.getHTML(); this.editorState.update(value => value + 1); }, onSelectionUpdate: () => this.editorState.update(value => value + 1) }); }
  ngOnDestroy(): void { this.editor?.destroy(); }
  protected get isEdit(): boolean { return this.postId !== null; }
  protected isActive(name: string, attributes?: Record<string, unknown>): boolean { this.editorState(); return this.editor?.isActive(name, attributes) ?? false; }
  protected toggleBold(): void { this.editor?.chain().focus().toggleBold().run(); } protected toggleItalic(): void { this.editor?.chain().focus().toggleItalic().run(); } protected toggleBulletList(): void { this.editor?.chain().focus().toggleBulletList().run(); } protected toggleOrderedList(): void { this.editor?.chain().focus().toggleOrderedList().run(); } protected toggleHeading(): void { this.editor?.chain().focus().toggleHeading({ level: 2 }).run(); } protected undo(): void { this.editor?.chain().focus().undo().run(); } protected redo(): void { this.editor?.chain().focus().redo().run(); }
  protected editLink(): void { const editor = this.editor; if (!editor) return; const current = editor.getAttributes('link')['href'] as string | undefined; const url = prompt('Link-Adresse (https://… oder mailto:…)', current ?? ''); if (url === null) return; if (url.trim() === '') { editor.chain().focus().extendMarkRange('link').unsetLink().run(); return; } if (!/^(https?:\/\/|mailto:)/i.test(url.trim())) { this.error.set('Links müssen mit https://, http:// oder mailto: beginnen.'); return; } editor.chain().focus().extendMarkRange('link').setLink({ href: url.trim() }).run(); }
  protected async insertContentImage(event: Event): Promise<void> { const input = event.target as HTMLInputElement; const image = input.files?.[0] ?? null; if (!image) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(image.type) || image.size > 5 * 1024 * 1024) { this.error.set('Erlaubt sind PNG, JPEG oder WebP bis 5 MB.'); return; } try { const url = await this.news.uploadContentImage(image); this.editor?.chain().focus().setImage({ src: url, alt: image.name }).run(); } catch { this.error.set('Das Bild konnte nicht hochgeladen werden.'); } finally { input.value = ''; } }
  protected selectImage(event: Event): void { this.setImage((event.target as HTMLInputElement).files?.[0] ?? null); } protected dragOver(event: DragEvent): void { event.preventDefault(); } protected dropImage(event: DragEvent): void { event.preventDefault(); this.setImage(event.dataTransfer?.files.item(0) ?? null); } protected removeImage(): void { this.image = null; this.imagePreviewUrl.set(null); this.removeExistingImage.set(true); }
  protected async save(): Promise<void> { const bodyHtml = this.editor?.getHTML().trim() ?? this.bodyHtml.trim(); if (!this.title.trim() || !this.subtitle.trim() || this.isEmpty(bodyHtml)) { this.error.set('Bitte füllen Sie alle Pflichtfelder aus.'); return; } const data = new FormData(); data.set('title', this.title.trim()); data.set('subtitle', this.subtitle.trim()); data.set('bodyHtml', bodyHtml); data.set('publishedAt', this.publishedAt); data.set('showFrom', this.showFrom); data.set('showUntil', this.showUntil); data.set('isVisible', String(this.isVisible)); data.set('removeImage', String(this.removeExistingImage())); if (this.image) data.set('image', this.image); this.isSaving.set(true); this.error.set(''); try { if (this.postId === null) await this.news.create(data); else await this.news.update(this.postId, data); await this.router.navigateByUrl('/inhalte'); } catch { this.error.set('Der Beitrag konnte nicht gespeichert werden.'); } finally { this.isSaving.set(false); } }
  private async load(id: number): Promise<void> { this.isLoading.set(true); try { const post = await this.news.get(id); this.title = post.title; this.subtitle = post.subtitle; this.publishedAt = this.toInputValue(post.publishedAt); this.showFrom = post.showFrom ? this.toInputValue(post.showFrom) : ''; this.showUntil = post.showUntil ? this.toInputValue(post.showUntil) : ''; this.isVisible = post.isVisible; this.imagePreviewUrl.set(post.imageUrl); this.bodyHtml = post.bodyHtml; this.editor?.commands.setContent(post.bodyHtml); } catch { this.error.set('Der Beitrag konnte nicht geladen werden.'); } finally { this.isLoading.set(false); } }
  private setImage(file: File | null): void { if (!file) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 5 * 1024 * 1024) { this.error.set('Erlaubt sind PNG, JPEG oder WebP bis 5 MB.'); return; } this.image = file; this.removeExistingImage.set(false); this.imagePreviewUrl.set(URL.createObjectURL(file)); }
  private isEmpty(html: string): boolean { return html.replace(/<[^>]+>/g, '').replace(/&nbsp;/g, ' ').trim() === ''; } private toInputValue(value: string): string { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); }
}
